//* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xB0, 0x25, 0x8D, 0xE8, 0x7C, 0x8B, 0x08, 0xF2}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_INSECURE

#define ENCODERS_PAD_B { D1 }
#define ENCODERS_PAD_A { D0 }
#define ENCODER_RESOLUTION 2 

#define DEBOUNCE 10

#define DYNAMIC_KEYMAP_LAYER_COUNT 2